apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  uri: bW9uZ29kYitzcnY6Ly9uaWtoaWxuYWdwdXJlMjAzOjZPMDZRaUNmZ252d3dLVXNAbWFpbi13ZWItYXBwLXNoYWRvd25pay52MmlmcS5tb25nb2RiLm5ldC8/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5JmFwcE5hbWU9TWFpbi1XZWItYXBwLVNIQURPV05JSw==
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
data:
  secret: eG5sLWlubm92YXRpb25zLXNlY3VyZS1qd3Qtc2VjcmV0LWtleS0yMDI0 